### ISSUE TITLE
求数据库设计sql

### ISSUE THREAD

**Issue by HouChenggong** [qqxx6661/miaosha#1]
或者兼容最新的依赖吗，比如mybatis或者mysql8.x

**Comment by qqxx6661** [comment]
表结构SQL文件已经放在最新的commit里，晚上配合第三篇同步更新代码，今天晚上一定上线~

**Comment by qqxx6661** [comment]
已经提交新代码，对最新依赖的兼容性未知，代码只是简单的CRUD，应该没有特殊依赖问题。
