### ISSUE TITLE
消息队列接受者问题

### ISSUE THREAD

**Issue by Chionanthus** [qqxx6661/miaosha#11]
源码中似乎漏了公众号文章中的RabbitMQ的消费者，OrderMqReceiver 类。
然后OrderController中的createOrderByMq和createUserOrderWithMq这两个方法似乎功能类似，有冗余

**Comment by qqxx6661** [comment]
感谢PR，确实在代码中没有放。我是从自己的私有仓库搬运代码到这个public仓库的，所以可能漏掉了。 #12
