### ISSUE TITLE
并发安全问题

### ISSUE THREAD

**Issue by imyzt** [qqxx6661/miaosha#2]
请教一下作者，
commitId：7702b62f8f0570d7ac6d1298512b25691f1521fa  
代码 `cn.monitor4all.miaoshaservice.service.UserServiceImpl#addUserCount` 这个方法在高并发场景下，if == null的判断，会不会有安全性问题啊

**Comment by qqxx6661** [comment]
看了下，真的有某单个用户大量请求的话，确实会存在redis中访问次数统计错误的情况。比如读了之后并发写了缓存。真的要准确的次数，这里可以加个redis锁什么的。

不过要是单个用户也请求这么大量，估计早晚会被ban掉把，所以不准确看起来影响不是太大。
