### ISSUE TITLE
Please help me,run error

### ISSUE THREAD

**Issue by Thewolfinsociety** [qqxx6661/miaosha#5]
java.lang.IllegalArgumentException: Sources must not be empty

**Comment by qqxx6661** [comment]
Please describe your issus in detail.

**Comment by OnlyChange** [comment]
master分支编译出错

**Comment by qqxx6661** [comment]
你们好，编译报错是由于dao和service子项目编译依赖使用了spring-boot-maven-plugin导致打包成了fat jar，下游无法引用。已经修复了这个问题。测试已经可以打包和运行。如果还有问题可以重新打开issue并贴上错误日志。感谢反馈哦~
