### ISSUE TITLE
乐观锁下单问题

### ISSUE THREAD

**Issue by zth9** [qqxx6661/miaosha#6]
@Override
    public int createOptimisticOrder(int sid) {
        //校验库存
        Stock stock = checkStock(sid);
        //乐观锁更新库存
        saleStockOptimistic(stock);
        //创建订单
        createOrder(stock);
        return stock.getCount() - (stock.getSale()+1);
    }
这个方法应该对 saleStockOptimistic(stock);的返回值做判断，再决定是否下单吧？
boolean b = saleStockOptimistic(stock);
        if (!b){
            throw new RuntimeException("版本错误，下单失败");
        }

**Comment by qqxx6661** [comment]
是的，我刚看了下是有这个问题。底下的createOrderByMq方法倒是用了返回的布尔值，可能之前的忘记了。等晚点有空我加上吧，或者你可以提个PR。

**Comment by qqxx6661** [comment]
已经有好心的大佬帮忙写了
