### ISSUE TITLE
博客有更新3以后的文章吗？微信推文图片清晰度不够

### ISSUE THREAD

**Issue by ghdefe** [qqxx6661/miaosha#8]

**Comment by qqxx6661** [comment]
都更新了，可以找下博客园：后端技术漫谈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ghdefe <notifications@github.com&gt;
发送时间: 2020年9月29日 17:49
收件人: qqxx6661/miaosha <miaosha@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[qqxx6661/miaosha] 博客有更新3以后的文章吗？微信推文图片清晰度不够 (#8)

**Comment by ghdefe** [comment]
感谢，找到了
